# Site settings
title: Daniel Chapman - Personal Site
description: "The personal of Daniel Chapman "
author:
  name: "Daniel A. Chapman"
  email: "dachapman91@gmail.com"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title

# Plugins
gems:
  - jekyll-sitemap

# Custom variables
version: "1.0.0"
